
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificate-arn-config
data:
  certificate-arn: |
    {{ with secret "aws:arn:/revive/certificate_arn" }}
    {{ .Data.certificate_arn }}
    {{ end }}
