apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-external-dns
  labels:
    app: app-ingress
  annotations:
    # kubernetes.io/ingressClassName: "alb" 
    kubernetes.io/ingress.class: "alb" 

    alb.ingress.kubernetes.io/load-balancer-name: revive-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    # Heath check settings
    # alb.ingress.kubernetes.io/healthcheck-port: '80'
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port  
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    # SSH settings
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:637423375996:certificate/9cd9e56d-d429-4c17-b6db-66295ccfcf05
    # SSL Redirect Setting (http to https) all http will be redirected to https
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # External dns settings
    external-dns.alpha.kubernetes.io/hostname: ui.reviceapp.com, app.reviceapp.com
spec:
#   defaultBackend:
#     service:
#       name: ui
#       port:
#         number: 7777
  rules: 
    - host: ui.reviceapp.com 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port: 
                  number: 7777
    - host: assets.reviceapp.com 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assets
                port: 
                  number: 8080
    - host: carts.reviceapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carts
                port: 
                  number: 8080
    - host: catalog.reviceapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: catalog
                port: 
                  number: 8080
    - host: orders.reviceapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orders
                port: 
                  number: 8080
    - host: checkout.reviceapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkout
                port: 
                  number: 8080